// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pixiu/pixiu.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pixiu/pixiu.proto

package pixiu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type PixiuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PixiuRequest) Reset() {
	*x = PixiuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pixiu_pixiu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PixiuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixiuRequest) ProtoMessage() {}

func (x *PixiuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiu_pixiu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixiuRequest.ProtoReflect.Descriptor instead.
func (*PixiuRequest) Descriptor() ([]byte, []int) {
	return file_pixiu_pixiu_proto_rawDescGZIP(), []int{0}
}

func (x *PixiuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PixiuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type PixiuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PixiuReply) Reset() {
	*x = PixiuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pixiu_pixiu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PixiuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixiuReply) ProtoMessage() {}

func (x *PixiuReply) ProtoReflect() protoreflect.Message {
	mi := &file_pixiu_pixiu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixiuReply.ProtoReflect.Descriptor instead.
func (*PixiuReply) Descriptor() ([]byte, []int) {
	return file_pixiu_pixiu_proto_rawDescGZIP(), []int{1}
}

func (x *PixiuReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pixiu_pixiu_proto protoreflect.FileDescriptor

var file_pixiu_pixiu_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x69, 0x78, 0x69, 0x75, 0x2f, 0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x69, 0x78, 0x69, 0x75, 0x22, 0x32, 0x0a, 0x0c, 0x50, 0x69,
	0x78, 0x69, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26,
	0x0a, 0x0a, 0x50, 0x69, 0x78, 0x69, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3d, 0x0a, 0x05, 0x50, 0x69, 0x78, 0x69, 0x75, 0x12,
	0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x69, 0x78, 0x69, 0x75, 0x12, 0x13, 0x2e, 0x70, 0x69,
	0x78, 0x69, 0x75, 0x2e, 0x50, 0x69, 0x78, 0x69, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x50, 0x69, 0x78, 0x69, 0x75, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x6f, 0x2d, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x73, 0x65, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x73, 0x65, 0x2f, 0x70, 0x69, 0x78, 0x69,
	0x75, 0x2f, 0x70, 0x69, 0x78, 0x69, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pixiu_pixiu_proto_rawDescOnce sync.Once
	file_pixiu_pixiu_proto_rawDescData = file_pixiu_pixiu_proto_rawDesc
)

func file_pixiu_pixiu_proto_rawDescGZIP() []byte {
	file_pixiu_pixiu_proto_rawDescOnce.Do(func() {
		file_pixiu_pixiu_proto_rawDescData = protoimpl.X.CompressGZIP(file_pixiu_pixiu_proto_rawDescData)
	})
	return file_pixiu_pixiu_proto_rawDescData
}

var file_pixiu_pixiu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pixiu_pixiu_proto_goTypes = []interface{}{
	(*PixiuRequest)(nil), // 0: pixiu.PixiuRequest
	(*PixiuReply)(nil),   // 1: pixiu.PixiuReply
}
var file_pixiu_pixiu_proto_depIdxs = []int32{
	0, // 0: pixiu.Pixiu.GetPixiu:input_type -> pixiu.PixiuRequest
	1, // 1: pixiu.Pixiu.GetPixiu:output_type -> pixiu.PixiuReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pixiu_pixiu_proto_init() }
func file_pixiu_pixiu_proto_init() {
	if File_pixiu_pixiu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pixiu_pixiu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PixiuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pixiu_pixiu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PixiuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pixiu_pixiu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pixiu_pixiu_proto_goTypes,
		DependencyIndexes: file_pixiu_pixiu_proto_depIdxs,
		MessageInfos:      file_pixiu_pixiu_proto_msgTypes,
	}.Build()
	File_pixiu_pixiu_proto = out.File
	file_pixiu_pixiu_proto_rawDesc = nil
	file_pixiu_pixiu_proto_goTypes = nil
	file_pixiu_pixiu_proto_depIdxs = nil
}
