// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PixiuerClient is the client API for Pixiuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PixiuerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type pixiuerClient struct {
	cc grpc.ClientConnInterface
}

func NewPixiuerClient(cc grpc.ClientConnInterface) PixiuerClient {
	return &pixiuerClient{cc}
}

func (c *pixiuerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Pixiuer/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PixiuerServer is the server API for Pixiuer service.
// All implementations must embed UnimplementedPixiuerServer
// for forward compatibility
type PixiuerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedPixiuerServer()
}

// UnimplementedPixiuerServer must be embedded to have forward compatible implementations.
type UnimplementedPixiuerServer struct {
}

func (UnimplementedPixiuerServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedPixiuerServer) mustEmbedUnimplementedPixiuerServer() {}

// UnsafePixiuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PixiuerServer will
// result in compilation errors.
type UnsafePixiuerServer interface {
	mustEmbedUnimplementedPixiuerServer()
}

func RegisterPixiuerServer(s grpc.ServiceRegistrar, srv PixiuerServer) {
	s.RegisterService(&Pixiuer_ServiceDesc, srv)
}

func _Pixiuer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixiuerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Pixiuer/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixiuerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pixiuer_ServiceDesc is the grpc.ServiceDesc for Pixiuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pixiuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Pixiuer",
	HandlerType: (*PixiuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Pixiuer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
